### ISSUE TITLE
PolyLookup: When adding an "Output Selected Field", the field no longer locks and says "Please save the form first"

### ISSUE THREAD

**Issue by DiogoAlex** [khoait/DCE.PCF#130] opened 2024-08-09 14:15 UTC
**Component**

PolyLookup v1.5.0

**Describe the bug**

I've created a PolyLookup using a NtoN relationship to the Accounts table. I've also recetly added an "Output Selected Field" because I needed the GUID of the selected Accounts to do some work on Javascript.
But, something we noticed is that, when creating a new record the field is no longer being locked and saying "Please save the form first" and lets the users select the Accounts they want. Then, when the record is created those selected Accounts are deleted

**Steps to Reproduce**

1. Create a Poly Lookup with a NtoN relationship with any table
2. Add an "Output Selected field"
3. Try creating a new record
4. Select records on the Poly Lookup
5. Notice that after creating those records selected have disappeared

**Screenshots**

![image](https://github.com/user-attachments/assets/01f9ad12-4c9c-4d2c-9c1a-382d40bf17f5)
![image](https://github.com/user-attachments/assets/24a3b805-ec9e-4403-95d2-c375db214fd9)

**Comment by DiogoAlex** [comment] 2024-08-09 14:25
The obvious culprit of this issue is this If, but I'm not sure if you want to remove it?: https://github.com/khoait/DCE.PCF/blob/eede997c6a57778eae9b8f46dfc1f33a7d8f8abd/PolyLookupComponent/PolyLookup/components/PolyLookupControl.tsx#L484-L486

**Comment by khoait** [comment] 2024-08-10 10:41
hi @DiogoAlex, thanks for reporting. I tested from my side again and everything is working as intended as follows:
- when `Output selected field` is not configured, the control is not supported in Create form, and it should show the message `Please save the form first` (from your screenshot, `Team Distribution List` and `Individual Distribution List`)
- when `Output selected field` is configured, the control is available in Create form, you can select lookup records, it should show the placeholder `Select ...`, and the selected records should be outputted as json text in the Output Field. (the `Related Accounts` in your screenshot)

please note that, in model-driven app, we can't create associations/related records (N:N or 1:N), until the record is created first. You can see this behavior in any subgrid on the form, when you're in create form, the subgrid is read-only (in classic look) or hidden (in new look), you can't add anything to the subgrid until the form is saved.

the PolyLookup control tries to overcome this by saving the selected records as json objects to a field. but it won't associate the main record with the selected records when the form is saved, this job depends on the customizer/developer. you'll need to create some kind of logic to achieve this, it can be a cloud flow or a plugin. I have a sample plugin to deal with this scenario. Please see wiki here: https://github.com/khoait/DCE.PCF/wiki/PolyLookup#selected-items

hope it helps! cheers!

**Comment by khoait** [comment] 2024-12-06 13:23
closing this for now. feel free to reopen or create a new issue if needed. cheers!

**Closed by khoait** 2024-12-06 13:23 UTC
Labels: type: bug 🐛, component: PolyLookup
